<?php
require __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/lib.php';

use phpseclib3\Net\SSH2;
use phpseclib3\Net\SFTP;

// Increase limits for large file handling
ini_set('memory_limit', '512M');
set_time_limit(0);

$isCli = (PHP_SAPI === 'cli') && empty($_SERVER['REMOTE_ADDR']) && empty($_SERVER['HTTP_HOST']);
if (true) {
    $licenseValid = false;
    $licenseKey = '';
    if (!empty($_COOKIE['deploy_license'])) {
        $licenseKey = trim((string)$_COOKIE['deploy_license']);
    }
    if (($_SERVER['REQUEST_METHOD'] ?? '') === 'POST' && isset($_POST['license'])) {
        $licenseKey = trim((string)$_POST['license']);
    }
    if ($licenseKey === '' && isset($_POST['license_key'])) {
        $licenseKey = trim((string)$_POST['license_key']);
    }
    if ($licenseKey === '8080') {
        $licenseValid = true;
        setcookie('deploy_license', $licenseKey, time() + 60, '/', '', false, true);
    }
    if (!$licenseValid && $licenseKey !== '') {
        $dbPath = __DIR__ . '/../license_bot.db';
        if (is_file($dbPath)) {
            try {
                $pdo = new PDO('sqlite:' . $dbPath);
                $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
                $stmt = $pdo->prepare('SELECT status, expires_at FROM licenses WHERE license_key = :key LIMIT 1');
                $stmt->execute([':key' => $licenseKey]);
                $row = $stmt->fetch(PDO::FETCH_ASSOC);
                if ($row && $row['status'] === 'active' && isset($row['expires_at']) && $row['expires_at'] > gmdate('c')) {
                    $licenseValid = true;
                    $cookieTtl = 60;
                    if (!isset($_COOKIE['deploy_license']) || $_COOKIE['deploy_license'] !== $licenseKey) {
                        setcookie('deploy_license', $licenseKey, time() + $cookieTtl, '/', '', false, true);
                    } else {
                        setcookie('deploy_license', $licenseKey, time() + $cookieTtl, '/', '', false, true);
                    }
                }
            } catch (Throwable $e) {
            }
        }
    }
    if (!defined('DEPLOY_CURRENT_LICENSE')) {
        define('DEPLOY_CURRENT_LICENSE', $licenseKey);
    }
    if (!$licenseValid) {
        $isApi = (($_SERVER['REQUEST_METHOD'] ?? '') === 'POST' && isset($_GET['action']));
        if ($isApi) {
            $jsonActions = ['add_server', 'delete_server', 'save_server', 'test_connection', 'list_domains', 'list_managed_domains', 'domain_status'];
            if (!in_array($_GET['action'], $jsonActions, true)) {
                header('Content-Type: text/event-stream');
                header('Cache-Control: no-cache');
                header('Connection: keep-alive');
                $payload = json_encode(['message' => 'License required', 'type' => 'error', 'time' => date('H:i:s')]);
                echo "data: " . $payload . "\n\n";
            } else {
                header('Content-Type: application/json');
                echo json_encode(['status' => 'error', 'message' => 'License required']);
            }
        } else {
            header('Content-Type: text/html; charset=UTF-8');
            ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>L1mk Deployer License</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body { margin:0; padding:0; background:#020617; color:#e5e7eb; font-family:-apple-system,BlinkMacSystemFont,system-ui,sans-serif; display:flex; align-items:center; justify-content:center; min-height:100vh; }
        .card { background:#020617; border:1px solid #1f2937; border-radius:0.75rem; padding:1.75rem; width:100%; max-width:360px; box-shadow:0 20px 40px rgba(15,23,42,0.5); }
        .title { font-size:1rem; font-weight:600; margin-bottom:0.5rem; color:#f9fafb; }
        .subtitle { font-size:0.8rem; color:#9ca3af; margin-bottom:1.25rem; }
        .input { width:100%; padding:0.6rem 0.75rem; border-radius:0.5rem; border:1px solid #374151; background:#020617; color:#e5e7eb; font-size:0.85rem; box-sizing:border-box; }
        .input:focus { outline:none; border-color:#6366f1; }
        .btn { width:100%; margin-top:0.75rem; padding:0.65rem 0.75rem; border-radius:0.5rem; border:none; background:#6366f1; color:#f9fafb; font-size:0.85rem; font-weight:600; cursor:pointer; }
        .btn:hover { background:#4f46e5; }
        .note { margin-top:0.75rem; font-size:0.75rem; color:#6b7280; }
    </style>
</head>
<body>
    <div class="card">
        <div class="title">Enter License Key</div>
        <div class="subtitle">Use a valid license generated by the Telegram bot to unlock the deployer.</div>
        <form method="post">
            <input type="text" name="license" class="input" placeholder="XXXX-XXXX-XXXX-XXXX" required>
            <button type="submit" class="btn">Unlock Deployer</button>
        </form>
        <div class="note">If you do not have a license, contact the bot to purchase one.</div>
    </div>
</body>
</html>
<?php
        }
        exit;
    }
}

// --- Helper Functions ---

function sse_message($message, $type = 'info') {
    echo "data: " . json_encode(['message' => $message, 'type' => $type, 'time' => date('H:i:s')]) . "\n\n";
    if (ob_get_level() > 0) ob_flush();
    flush();
}

function get_used_identifiers($servers) {
    $slugs = [];
    $paths = [];
    foreach ($servers as $s) {
        if (!empty($s['rotation_slugs']) && is_array($s['rotation_slugs'])) {
            foreach ($s['rotation_slugs'] as $sl) $slugs[$sl] = true;
        }
        if (!empty($s['rotation_path'])) {
            $paths[$s['rotation_path']] = true;
        }
    }
    return [$slugs, $paths];
}



// --- Config Handling ---

$diskDir = '/data/deploy_config.json';
if (is_dir($diskDir) && is_writable($diskDir)) {
    $configFile = $diskDir . '/deploy_config.json';
} else {
    $configFile = __DIR__ . '/deploy_config.json';
}
$savedServers = [];
if (file_exists($configFile)) {
    $content = file_get_contents($configFile);
    $data = json_decode($content, true);
    if (is_array($data)) {
        // Migration: Check if it's the old single-object format
        if (isset($data['host']) && !isset($data[0])) {
            $savedServers[] = $data;
        } else {
            $savedServers = $data;
        }
    }
}

$currentLicense = defined('DEPLOY_CURRENT_LICENSE') ? DEPLOY_CURRENT_LICENSE : '';

if ($currentLicense !== '' && $currentLicense !== '8080') {
    $filtered = [];
    foreach ($savedServers as $srv) {
        if (!is_array($srv)) continue;
        if (!isset($srv['license_key']) || $srv['license_key'] !== $currentLicense) continue;
        $filtered[] = $srv;
    }
    $savedServers = $filtered;
}

foreach ($savedServers as &$srv) {
    if (!is_array($srv)) continue;
    if (!array_key_exists('main_domain', $srv) && array_key_exists('domain', $srv)) {
        $srv['main_domain'] = $srv['domain'];
    }
    if (!array_key_exists('domains', $srv)) {
        $srv['domains'] = [];
    }
    if (is_string($srv['domains'])) {
        $srv['domains'] = normalize_domains_list($srv['domains']);
    }
    if (!is_array($srv['domains'])) {
        $srv['domains'] = [];
    }
    $srv['main_domain'] = normalize_domain($srv['main_domain'] ?? '');
    $srv['domains'] = array_values(array_filter(array_map('normalize_domain', $srv['domains'])));
    $srv['domains'] = array_values(array_filter(array_unique($srv['domains']), fn($d) => $d !== '' && $d !== $srv['main_domain']));
    if (!array_key_exists('rotation_enabled', $srv)) {
        $srv['rotation_enabled'] = false;
    } else {
        $srv['rotation_enabled'] = (bool)$srv['rotation_enabled'];
    }
}
unset($srv);

// --- API Handling ---

if (($_SERVER['REQUEST_METHOD'] ?? '') === 'POST' && isset($_GET['action'])) {
    // For SSE actions, headers are set later
    if (!in_array($_GET['action'], ['add_server', 'delete_server', 'save_server', 'test_connection', 'list_domains', 'list_managed_domains', 'domain_status'])) {
        header('Content-Type: text/event-stream');
        header('Cache-Control: no-cache');
        header('Connection: keep-alive');
    } else {
        header('Content-Type: application/json');
    }

    $req = parse_deploy_request($_POST);
    extract($req);

    // Load rotation details from saved server if available
    $rotation_slugs = [];
    $rotation_path = '';
    if (!empty($server_id)) {
        foreach ($savedServers as $s) {
            if (($s['id'] ?? '') === $server_id) {
                $rotation_slugs = $s['rotation_slugs'] ?? [];
                $rotation_path = $s['rotation_path'] ?? '';
                break;
            }
        }
    }

    if ($action === 'test_connection') {
        try {
            $ssh = new SSH2($host, $port);
            if (!$ssh->login($user, $password)) {
                echo json_encode(['status' => 'error', 'message' => 'Login failed. Check credentials.']);
            } else {
                echo json_encode(['status' => 'success', 'message' => 'Connection successful!']);
            }
        } catch (Exception $e) {
             echo json_encode(['status' => 'error', 'message' => 'Connection error: ' . $e->getMessage()]);
        }
        exit;
    }

    if ($action === 'list_domains') {
        try {
            [$ssh, $sudo] = ssh_connect($host, $port, $user, $password);
            $cmd = $sudo . "sh -lc " . escapeshellarg("awk '/server_name/{for(i=2;i<=NF;i++) print \$i}' /etc/nginx/sites-enabled/* 2>/dev/null | tr -d ';' | sort -u");
            $raw = (string)$ssh->exec($cmd);
            $lines = preg_split('/\r?\n/', trim($raw));
            $domainsOut = [];
            foreach ($lines as $line) {
                $d = normalize_domain($line);
                if ($d === '' || $d === '_') continue;
                $domainsOut[$d] = true;
            }
            $domainsOut = array_values(array_keys($domainsOut));
            sort($domainsOut);

            echo json_encode(['status' => 'success', 'domains' => $domainsOut]);
            exit;
        } catch (Exception $e) {
            echo json_encode(['status' => 'error', 'message' => 'Domain fetch error: ' . $e->getMessage()]);
            exit;
        }
    }

    if ($action === 'list_managed_domains') {
        try {
            [$ssh, $sudo] = ssh_connect($host, $port, $user, $password);
            $configKey = nginx_config_key($main_domain);
            $cmd = $sudo . "sh -lc " . escapeshellarg("if [ -f /etc/nginx/sites-enabled/$configKey ]; then awk '/server_name/{for(i=2;i<=NF;i++) print $i}' /etc/nginx/sites-enabled/$configKey; fi");
            $raw = (string)$ssh->exec($cmd);
            $lines = preg_split('/\r?\n/', trim($raw));
            $domainsOut = [];
            foreach ($lines as $line) {
                $clean = trim(str_replace(';', '', $line));
                $d = normalize_domain($clean);
                if ($d === '' || $d === '_') continue;
                $domainsOut[$d] = true;
            }
            $domainsOut = array_values(array_keys($domainsOut));
            sort($domainsOut);

            echo json_encode(['status' => 'success', 'domains' => $domainsOut, 'config_key' => $configKey]);
            exit;
        } catch (Exception $e) {
            echo json_encode(['status' => 'error', 'message' => 'Domain fetch error: ' . $e->getMessage()]);
            exit;
        }
    }

    if ($action === 'domain_status') {
        $targets = [];
        if ($main_domain !== '') $targets[] = $main_domain;
        foreach ($domains as $d) if ($d !== '' && $d !== $main_domain) $targets[] = $d;
        $targets = array_values(array_unique($targets));

        // 1. External Check (Parallel curl_multi)
        $mh = curl_multi_init();
        $handles = [];
        foreach ($targets as $d) {
            foreach (['http', 'https'] as $proto) {
                $ch = curl_init();
                curl_setopt($ch, CURLOPT_URL, "$proto://$d");
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                curl_setopt($ch, CURLOPT_NOBODY, true);
                curl_setopt($ch, CURLOPT_TIMEOUT, 5);
                curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
                curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
                curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
                curl_multi_add_handle($mh, $ch);
                $handles["$proto://$d"] = ['ch' => $ch, 'domain' => $d, 'proto' => $proto];
            }
        }

        $active = null;
        do {
            $mrc = curl_multi_exec($mh, $active);
        } while ($mrc == CURLM_CALL_MULTI_PERFORM);

        while ($active && $mrc == CURLM_OK) {
            if (curl_multi_select($mh) != -1) {
                do {
                    $mrc = curl_multi_exec($mh, $active);
                } while ($mrc == CURLM_CALL_MULTI_PERFORM);
            }
        }

        $results = [];
        foreach ($handles as $key => $h) {
            $info = curl_getinfo($h['ch']);
            $code = $info['http_code'];
            $ip = $info['primary_ip'];
            
            if (!isset($results[$h['domain']])) {
                $results[$h['domain']] = ['http' => 0, 'https' => 0, 'ip' => ''];
            }
            $results[$h['domain']][$h['proto']] = $code;
            if ($ip && !$results[$h['domain']]['ip']) {
                $results[$h['domain']]['ip'] = $ip;
            }
            
            curl_multi_remove_handle($mh, $h['ch']);
        }

        // 2. Internal Check (Optimized SSH - Single Command)
        $localCodes = [];
        try {
            [$ssh, $sudo] = ssh_connect($host, $port, $user, $password);
            
            $cmdList = [];
            foreach ($targets as $d) {
                $cmdList[] = "code=$(curl -Is -o /dev/null -w '%{http_code}' -H 'Host: $d' http://127.0.0.1 --max-time 2 || echo 0); echo \"$d:\$code\"";
            }
            $fullCmd = $sudo . "sh -c " . escapeshellarg(implode('; ', $cmdList));
            
            $rawOut = (string)$ssh->exec($fullCmd);
            $lines = explode("\n", trim($rawOut));
            foreach ($lines as $line) {
                if (strpos($line, ':') !== false) {
                    [$d, $c] = explode(':', trim($line), 2);
                    $localCodes[$d] = intval($c);
                }
            }
        } catch (Exception $e) {
            // SSH failed or skipped
        }

        $out = [];
        foreach ($targets as $d) {
            $httpCode = $results[$d]['http'] ?? 0;
            $httpsCode = $results[$d]['https'] ?? 0;
            $localCode = $localCodes[$d] ?? 0;
            $dnsIp = $results[$d]['ip'] ?? '';
            
            if ($dnsIp === '') {
                $dnsIp = gethostbyname($d);
                if ($dnsIp === $d) $dnsIp = '';
            }
            
            $matchesHost = ($dnsIp !== '' && $host !== '' && $dnsIp === $host);
            $localLive = ($localCode >= 200 && $localCode < 400);
            $live = ($httpCode >= 200 && $httpCode < 400) || ($httpsCode >= 200 && $httpsCode < 400) || $localLive;
            
            $out[] = [
                'domain' => $d,
                'dns_ip' => $dnsIp,
                'matches_host' => $matchesHost,
                'http_code' => $httpCode,
                'https_code' => $httpsCode,
                'local_code' => $localCode,
                'live' => $live,
                'local_live' => $localLive
            ];
        }
        echo json_encode(['status' => 'success', 'statuses' => $out]);
        exit;
    }

    if ($action === 'add_server') {
        $currentLicense = defined('DEPLOY_CURRENT_LICENSE') ? DEPLOY_CURRENT_LICENSE : '';
        if ($currentLicense !== '' && $currentLicense !== '8080') {
            $activeCount = 0;
            foreach ($savedServers as $srv) {
                if (isset($srv['license_key']) && $srv['license_key'] === $currentLicense) {
                    $activeCount++;
                }
            }
            if ($activeCount >= 1) {
                echo json_encode(['status' => 'error', 'message' => 'This license already has an active VPS. Delete it before adding another.']);
                exit;
            }
        }

        try {
            [$ssh, $sudo] = ssh_connect($host, $port, $user, $password);
        } catch (Exception $e) {
            echo json_encode(['status' => 'error', 'message' => 'Connection error: ' . $e->getMessage()]);
            exit;
        }

        // 2. Save
        $rotation_slugs = [];
        $rotation_path = '';

        if ($rotation_enabled) {
            [$usedSlugs, $usedPaths] = get_used_identifiers($savedServers);

            // Generate unique slug
            for ($i = 0; $i < 50; $i++) {
                $candidate = generate_random_string(5);
                if (!isset($usedSlugs[$candidate])) {
                    $rotation_slugs = [$candidate];
                    break;
                }
            }
            // Fallback if loop fails
            if (empty($rotation_slugs)) {
                $rotation_slugs = [generate_random_string(5)];
            }

            // Generate unique path
            for ($i = 0; $i < 50; $i++) {
                $candidate = generate_random_string(20);
                if (!isset($usedPaths[$candidate])) {
                    $rotation_path = $candidate;
                    break;
                }
            }
            if (empty($rotation_path)) {
                $rotation_path = generate_random_string(20);
            }
        }

        $newServer = [
            'host' => $host,
            'user' => $user,
            'password' => $password,
            'port' => $port,
            'path' => $path,
            'main_domain' => $main_domain,
            'domains' => $domains,
            'rotation_enabled' => $rotation_enabled,
            'wildcard_enabled' => $wildcard_enabled,
            'rotation_slugs' => $rotation_slugs,
            'rotation_path' => $rotation_path,
            'local_path' => $local_path,
            'id' => uniqid('srv_'),
            'license_key' => defined('DEPLOY_CURRENT_LICENSE') ? DEPLOY_CURRENT_LICENSE : ''
        ];
        
        $savedServers[] = $newServer;
        file_put_contents($configFile, json_encode($savedServers, JSON_PRETTY_PRINT));
        
        echo json_encode(['status' => 'success', 'message' => 'Server added successfully.', 'server' => $newServer]);
        exit;
    }
    
    if ($action === 'delete_server') {
        $idToDelete = $_POST['server_id'] ?? '';
        $newServers = [];
        foreach ($savedServers as $srv) {
            if (($srv['id'] ?? '') !== $idToDelete) {
                $newServers[] = $srv;
            }
        }
        $savedServers = $newServers;
        file_put_contents($configFile, json_encode($savedServers, JSON_PRETTY_PRINT));
        echo json_encode(['status' => 'success', 'message' => 'Server deleted.']);
        exit;
    }

    if ($action === 'save_server') {
        // Update existing server
        $idToUpdate = $_POST['server_id'] ?? '';
        foreach ($savedServers as &$srv) {
            if (($srv['id'] ?? '') === $idToUpdate) {
                $srv['host'] = $host;
                $srv['user'] = $user;
                $srv['password'] = $password;
                $srv['port'] = $port;
                $srv['path'] = $path;
                $srv['main_domain'] = $main_domain;
                $srv['domains'] = $domains;
                $srv['rotation_enabled'] = $rotation_enabled;
                $srv['wildcard_enabled'] = $wildcard_enabled;
                if (array_key_exists('domain', $srv)) unset($srv['domain']);
                if ($rotation_enabled) {
                    [$usedSlugs, $usedPaths] = get_used_identifiers($savedServers);

                    if (empty($srv['rotation_slugs'])) {
                        for ($i = 0; $i < 50; $i++) {
                            $candidate = generate_random_string(5);
                            if (!isset($usedSlugs[$candidate])) {
                                $srv['rotation_slugs'] = [$candidate];
                                break;
                            }
                        }
                        if (empty($srv['rotation_slugs'])) $srv['rotation_slugs'] = [generate_random_string(5)];
                    }
                    if (empty($srv['rotation_path'])) {
                        if (!empty($rotation_path)) {
                            $srv['rotation_path'] = $rotation_path;
                        } else {
                            for ($i = 0; $i < 50; $i++) {
                                $candidate = generate_random_string(20);
                                if (!isset($usedPaths[$candidate])) {
                                    $srv['rotation_path'] = $candidate;
                                    break;
                                }
                            }
                            if (empty($srv['rotation_path'])) $srv['rotation_path'] = generate_random_string(20);
                        }
                    }
                }
                $srv['local_path'] = $local_path;
                break;
            }
        }
        file_put_contents($configFile, json_encode($savedServers, JSON_PRETTY_PRINT));
        echo json_encode(['status' => 'success', 'message' => 'Server updated.']);
        exit;
    }

    if ($action === 'apply_domains') {
        header('Content-Type: text/event-stream');
        header('Cache-Control: no-cache');
        header('Connection: keep-alive');

        sse_message("🌐 Applying domains to Nginx (no file deploy)...");
        try {
            [$ssh, $sudo] = ssh_connect($host, $port, $user, $password);
            $configKey = nginx_config_key($main_domain);

            // Check if Let's Encrypt certificates exist
            $useLetsEncrypt = false;
            if ($main_domain !== '') {
                $checkLe = $ssh->exec("if [ -f /etc/letsencrypt/live/" . escapeshellarg($main_domain) . "/fullchain.pem ]; then echo 'EXISTS'; fi");
                if (trim($checkLe) === 'EXISTS') {
                    $useLetsEncrypt = true;
                    sse_message("ℹ️ Found Let's Encrypt certificates. Using them.");
                }
            }

            $nginxConfig = get_nginx_config_multi($main_domain, $domains, $path, $rotation_enabled, $wildcard_enabled, $rotation_path, $rotation_slugs, $useLetsEncrypt);

            $phpSock = get_php_sock($ssh);
            $nginxConfig = str_replace('/var/run/php/php-fpm.sock', $phpSock, $nginxConfig);

            // Cleanup conflicting standalone configs for alias domains
            foreach ($domains as $d) {
                if ($d === '' || $d === $main_domain) continue;
                $aliasKey = nginx_config_key($d);
                // Only remove if it's not the main config key (just in case)
                if ($aliasKey !== $configKey) {
                    $ssh->exec("$sudo rm /etc/nginx/sites-enabled/$aliasKey 2>/dev/null || true");
                    $ssh->exec("$sudo rm /etc/nginx/sites-available/$aliasKey 2>/dev/null || true");
                }
            }

            if ($main_domain === '') {
                $ssh->exec("$sudo rm /etc/nginx/sites-enabled/default 2>/dev/null || true");
            }

            sse_message("📝 Writing Nginx config: $configKey");
            write_nginx($ssh, $sudo, $configKey, $nginxConfig);

            sse_message("✅ Domains applied.", 'success');
            sse_message("DONE_APPLY_DOMAINS");
            exit;
        } catch (Exception $e) {
            sse_message("❌ Apply domains error: " . $e->getMessage(), 'error');
            exit;
        }
    }

    if ($action === 'remove_domains_only') {
        header('Content-Type: text/event-stream');
        header('Cache-Control: no-cache');
        header('Connection: keep-alive');

        sse_message("🧹 Removing managed domains from Nginx (keeping files)...");
        try {
            [$ssh, $sudo] = ssh_connect($host, $port, $user, $password);
            $configKey = nginx_config_key($main_domain);

            sse_message("🗑️ Removing Nginx config: $configKey");
            remove_nginx_config($ssh, $sudo, $configKey);

            sse_message("✅ Domains removed from Nginx.", 'success');
            sse_message("DONE_REMOVE_DOMAINS");
            exit;
        } catch (Exception $e) {
            sse_message("❌ Remove domains error: " . $e->getMessage(), 'error');
            exit;
        }
    }

    if ($action === 'update_page') {
        sse_start("Page Update", "$user@$host");
        $sourceDir = rtrim($local_path, '/');
        
        if (!is_dir($sourceDir)) {
             sse_message("❌ Local source directory does not exist: $sourceDir", 'error');
             exit;
        }

        sse_message("📦 Zipping page assets...");
        $zipFile = __DIR__ . '/deploy_package.zip';
        if (!zip_project_page($sourceDir, $zipFile)) {
            sse_message("❌ Failed to zip page assets.", 'error');
            exit;
        }

        // 2. Connect & Upload
        sse_message("🔌 Connecting to VPS...");
        try {
            [$ssh, $sudo] = ssh_connect($host, $port, $user, $password);
            $sftp = new SFTP($host, $port);
            if (!$sftp->login($user, $password)) throw new Exception("SFTP Login failed.");
            
            sse_message("⬆️ Uploading files...");
            $ssh->exec("mkdir -p " . escapeshellarg($path));
            if (!$sftp->put($path . '/deploy_package.zip', $zipFile, SFTP::SOURCE_LOCAL_FILE)) {
                throw new Exception("Upload failed.");
            }
        } catch (Exception $e) {
            sse_message("❌ Connection/Upload Error: " . $e->getMessage(), 'error');
            unlink($zipFile);
            exit;
        }

        sse_message("⚙️ Applying page updates...");
        $commands = [
            "cd " . escapeshellarg($path) . " && unzip -o deploy_package.zip",
            "rm " . escapeshellarg($path) . "/deploy_package.zip",
            "chown -R www-data:www-data " . escapeshellarg($path),
            "chmod -R 755 " . escapeshellarg($path),
            "mkdir -p " . escapeshellarg($path) . "/session_data",
            "chmod -R 777 " . escapeshellarg($path) . "/session_data",
            "chmod 666 " . escapeshellarg($path) . "/database.sqlite"
        ];

        foreach ($commands as $cmd) {
            $ssh->exec($sudo . $cmd);
        }

        unlink($zipFile);
        sse_message("✅ Page updated successfully.", 'success');
        sse_finish("DONE_DEPLOY", "Page Update");
        exit;
    }

    if ($action === 'update_code') {
        sse_start("Code Update", "$user@$host");
        $sourceDir = rtrim($local_path, '/');
        
        if (!is_dir($sourceDir)) {
             sse_message("❌ Local source directory does not exist: $sourceDir", 'error');
             exit;
        }

        sse_message("📦 Zipping project files...");
        $zipFile = __DIR__ . '/deploy_package.zip';
        if (!zip_project($sourceDir, $zipFile)) {
            sse_message("❌ Failed to zip project.", 'error');
            exit;
        }

        sse_message("🔌 Connecting to VPS...");
        try {
            [$ssh, $sudo] = ssh_connect($host, $port, $user, $password);
            $sftp = new SFTP($host, $port);
            if (!$sftp->login($user, $password)) throw new Exception("SFTP Login failed.");
            
            sse_message("⬆️ Uploading files...");
            $ssh->exec("mkdir -p " . escapeshellarg($path));
            if (!$sftp->put($path . '/deploy_package.zip', $zipFile, SFTP::SOURCE_LOCAL_FILE)) {
                throw new Exception("Upload failed.");
            }
        } catch (Exception $e) {
            sse_message("❌ Connection/Upload Error: " . $e->getMessage(), 'error');
            unlink($zipFile);
            exit;
        }

        sse_message("⚙️ Applying updates...");
        $commands = [
            "cd " . escapeshellarg($path) . " && unzip -o deploy_package.zip",
            "rm " . escapeshellarg($path) . "/deploy_package.zip",
            "chown -R www-data:www-data " . escapeshellarg($path),
            "chmod -R 755 " . escapeshellarg($path),
            "chmod -R 777 " . escapeshellarg($path) . "/session_data",
            "chmod 666 " . escapeshellarg($path) . "/database.sqlite"
        ];

        foreach ($commands as $cmd) {
            $ssh->exec($sudo . $cmd);
        }

        sse_message("🔄 Restarting worker...");
        $ssh->exec("cd " . escapeshellarg($path) . " && " . $sudo . "pkill -f 'php index.php worker' || true");
        
        if (method_exists($ssh, 'disconnect')) $ssh->disconnect();
        $ssh = null;
        try {
            $ssh = new SSH2($host, $port);
            if ($ssh->login($user, $password)) {
                $workerCmd = "cd " . escapeshellarg($path) . " && ";
                if ($user === 'root') {
                    $workerCmd .= "nohup php index.php worker > worker.log 2>&1 < /dev/null & echo 'STARTED'";
                } else {
                    $workerCmd .= "sudo -u www-data nohup php index.php worker > worker.log 2>&1 < /dev/null & echo 'STARTED'";
                }
                $output = $ssh->exec($workerCmd);
                sse_message("Worker Output: " . $output);
            }
        } catch (Exception $e) {
             sse_message("⚠️ Worker restart warning: " . $e->getMessage(), 'warning');
        }

        unlink($zipFile);
        sse_message("✅ Code updated successfully.", 'success');
        sse_finish("DONE_DEPLOY", "Code Update");
        exit;
    }

    if ($action === 'deploy' || $action === 'update') {
        $modeLabel = ($action === 'update') ? 'Update' : 'Deployment';
        sse_start($modeLabel, "$user@$host");
        $sourceDir = rtrim($local_path, '/');
        
        if (!is_dir($sourceDir)) {
             sse_message("❌ Local source directory does not exist: $sourceDir", 'error');
             exit;
        }

        $syntaxCheck = check_php_syntax($sourceDir);
        if (!$syntaxCheck['success']) {
            sse_message("❌ Syntax Error in " . $syntaxCheck['file'], 'error');
            sse_message($syntaxCheck['error'], 'error');
            sse_message("⚠️ Deployment Aborted due to syntax error.");
            exit;
        }
        sse_message("✅ Syntax Check Passed.");

        // 1. Zip Project
        sse_message("📦 Zipping project files from: $local_path");
        $zipFile = __DIR__ . '/deploy_package.zip';
        
        if (zip_project($sourceDir, $zipFile)) {
            sse_message("✅ Project zipped successfully (" . round(filesize($zipFile) / 1024 / 1024, 2) . " MB).");
        } else {
            sse_message("❌ Failed to zip project.", 'error');
            exit;
        }

        // 2. Connect via SSH
        sse_message("🔌 Connecting to VPS...");
        try {
            [$ssh, $sudo] = ssh_connect($host, $port, $user, $password);
            sse_message("✅ SSH Connected.");

            // 2.1 Install Dependencies (If missing)
            sse_message("🛠️ Checking and installing system dependencies (this may take a while)...");
            
            // Non-interactive apt
            $ssh->exec("export DEBIAN_FRONTEND=noninteractive");
            
            // Check for unzip and php and bcmath and pdo_sqlite and node and npm
            $checkDeps = $ssh->exec("if command -v unzip >/dev/null && command -v php >/dev/null && command -v node >/dev/null && command -v npm >/dev/null && php -m | grep -q bcmath && php -m | grep -q pdo_sqlite; then echo 'INSTALLED'; fi");
            if (trim($checkDeps) !== 'INSTALLED') {
                sse_message("📦 Installing: unzip, nginx, php, extensions, nodejs, npm...");
                $ssh->setTimeout(600); // Allow 10 minutes for install
                $ssh->exec("$sudo apt-get update");
                $ssh->exec("$sudo apt-get install -y curl gnupg"); // Ensure curl/gnupg for node setup
                
                // Install Node.js 20.x
                sse_message("📦 Setting up Node.js 20.x...");
                $ssh->exec("curl -fsSL https://deb.nodesource.com/setup_20.x | $sudo -E bash -");
                
                $ssh->exec("$sudo apt-get install -y unzip nginx php-fpm php-cli php-curl php-mbstring php-xml php-zip php-sqlite3 php-bcmath libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2 ca-certificates fonts-liberation nodejs npm");
                sse_message("✅ Dependencies installed.");
            } else {
                sse_message("✅ Dependencies already present.");
            }

            $sftp = new SFTP($host, $port);
            if (!$sftp->login($user, $password)) {
                throw new Exception("SFTP Login failed.");
            }
            sse_message("✅ SFTP Connected.");

        } catch (Exception $e) {
            sse_message("❌ Connection Error: " . $e->getMessage(), 'error');
            unlink($zipFile);
            exit;
        }

        // 3. Upload Zip
        sse_message("⬆️ Uploading project files...");
        try {
            // Ensure remote directory exists
            $ssh->exec("mkdir -p " . escapeshellarg($path));
            
            // Upload
            if ($sftp->put($path . '/deploy_package.zip', $zipFile, SFTP::SOURCE_LOCAL_FILE)) {
                sse_message("✅ Upload complete.");
            } else {
                throw new Exception("Upload failed.");
            }
        } catch (Exception $e) {
            sse_message("❌ Upload Error: " . $e->getMessage(), 'error');
            unlink($zipFile);
            exit;
        }

        // 4. Remote Execution & Nginx Setup
        sse_message("⚙️ Configuring remote environment...");

        // Reconnect for execution phase
        if (method_exists($ssh, 'disconnect')) $ssh->disconnect();
        $ssh = null; // Force cleanup
        
        $ssh = ssh_reconnect($ssh, $host, $port, $user, $password);
        
        // Dynamic PHP FPM socket detection
        $phpSock = get_php_sock($ssh);
        sse_message("ℹ️ Detected PHP Socket: $phpSock");

        // Read local ENC_KEY
        $localEnvPath = $sourceDir . '/.env';
        $encKey = '';
        if (file_exists($localEnvPath)) {
            $envContent = file_get_contents($localEnvPath);
            if (preg_match('/^ENC_KEY=(.*)$/m', $envContent, $matches)) {
                $encKey = trim($matches[1]);
                sse_message("🔑 Found local ENC_KEY, will inject to remote.");
            }
        }

        $commands = [
            // Create backup
            "mkdir -p " . escapeshellarg($path) . "/backups",
        "cd " . escapeshellarg($path) . " && if [ -f index.php ]; then echo 'Creating backup...'; zip -q -r backups/backup_$(date +%Y%m%d_%H%M%S).zip . -x 'backups/*' 'deploy_package.zip' 'session_data/*' 'storage/logs/*'; fi",
        // Rotate backups (keep last 5)
        "cd " . escapeshellarg($path) . "/backups && ls -t *.zip 2>/dev/null | tail -n +6 | xargs -r rm --",
        
        "cd " . escapeshellarg($path) . " && unzip -o deploy_package.zip",
        "cd " . escapeshellarg($path) . " && rm deploy_package.zip",
        "cd " . escapeshellarg($path) . " && if [ ! -f config.json.enc ]; then cp config.example.json config.json.enc 2>/dev/null || true; fi",
        // Write deployment info
        "echo " . escapeshellarg(base64_encode(json_encode([
            'main_domain' => $main_domain,
            'rotation_path' => $rotation_path,
            'rotation_slugs' => $rotation_slugs
        ]))) . " | base64 -d > " . escapeshellarg($path) . "/deployment.json",
        "chmod 644 " . escapeshellarg($path) . "/deployment.json",
        // Permissions
        "chown -R www-data:www-data " . escapeshellarg($path),
        "chmod -R 755 " . escapeshellarg($path),
        "mkdir -p " . escapeshellarg($path) . "/session_data",
        "chmod -R 777 " . escapeshellarg($path) . "/session_data",
        // Ensure SQLite writable
        "touch " . escapeshellarg($path) . "/database.sqlite",
        "chown www-data:www-data " . escapeshellarg($path) . "/database.sqlite",
        "chmod 666 " . escapeshellarg($path) . "/database.sqlite",
        // Composer
        "if ! command -v composer &> /dev/null; then echo 'Installing Composer...'; curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer; fi",
        "cd " . escapeshellarg($path) . " && export COMPOSER_ALLOW_SUPERUSER=1 && composer install --no-dev --optimize-autoloader",
        // NPM
        "if ! command -v npm &> /dev/null; then echo 'Warning: Node/NPM not found. Skipping frontend build.'; else cd " . escapeshellarg($path) . " && npm install --production; fi"
    ];

        if ($encKey !== '') {
            $commands[] = "cd " . escapeshellarg($path) . " && echo " . escapeshellarg("ENC_KEY=" . $encKey) . " > .env";
        }

        foreach ($commands as $cmd) {
            sse_message("Exec: $cmd");
            $output = $ssh->exec($cmd);
            if (trim($output)) sse_message("Output: " . trim($output), 'info');
        }

        // Start Worker separately
        sse_message("🚀 Starting Worker Process...");
        
        // Reconnect for worker to avoid channel issues
        if (method_exists($ssh, 'disconnect')) $ssh->disconnect();
        $ssh = null;

        try {
            $ssh = new SSH2($host, $port);
            if ($ssh->login($user, $password)) {
                $ssh->exec("cd " . escapeshellarg($path) . " && pkill -f 'php index.php worker' || true");
                
                $workerCmd = "cd " . escapeshellarg($path) . " && ";
                if ($user === 'root') {
                    $workerCmd .= "nohup php index.php worker > worker.log 2>&1 < /dev/null & echo 'STARTED'";
                } else {
                    $workerCmd .= "sudo -u www-data nohup php index.php worker > worker.log 2>&1 < /dev/null & echo 'STARTED'";
                }
                $output = $ssh->exec($workerCmd);
                sse_message("Worker Output: " . $output);
            } else {
                sse_message("❌ Failed to reconnect for worker start", 'error');
            }
        } catch (Exception $e) {
            sse_message("⚠️ Worker start warning: " . $e->getMessage(), 'warning');
        }

        // 5. SSL Setup (Self-Signed for Cloudflare Full)
        sse_message("🔒 Checking SSL certificates...");
        // Reconnect for SSL to avoid channel issues
        if (method_exists($ssh, 'disconnect')) $ssh->disconnect();
        $ssh = null;
        try {
            $ssh = new SSH2($host, $port);
            if (!$ssh->login($user, $password)) {
                 sse_message("❌ Failed to reconnect for SSL setup", 'error');
            } else {
                 $sudo = ($user === 'root') ? '' : 'sudo ';
                 $ssh->exec("$sudo mkdir -p /etc/nginx/ssl");
                 $checkCert = $ssh->exec("if [ -f /etc/nginx/ssl/selfsigned.crt ]; then echo 'EXISTS'; fi");
                 
                 if (trim($checkCert) !== 'EXISTS') {
                     sse_message("🔑 Generating self-signed certificate...");
                     $ssh->setTimeout(60); // Give openssl time
                     // Ensure openssl is installed
                     $ssh->exec("$sudo apt-get install -y openssl");
                     // Generate cert
                     $genCmd = "$sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/selfsigned.key -out /etc/nginx/ssl/selfsigned.crt -subj '/C=US/ST=State/L=City/O=Organization/CN=localhost'";
                     $ssh->exec($genCmd);
                     
                     // Verify generation
                     $checkAgain = $ssh->exec("if [ -f /etc/nginx/ssl/selfsigned.crt ]; then echo 'CREATED'; fi");
                     if (trim($checkAgain) === 'CREATED') {
                         sse_message("✅ Certificate generated.");
                     } else {
                         sse_message("⚠️ Certificate generation failed. Nginx SSL might fail.", 'warning');
                     }
                 } else {
                     sse_message("✅ Certificate already exists.");
                 }
            }
        } catch (Exception $e) {
            sse_message("⚠️ SSL Setup Warning: " . $e->getMessage(), 'warning');
        }

        // 6. Nginx Configuration
        try {
            $ssh = ssh_reconnect($ssh, $host, $port, $user, $password);
            $targetLabel = $main_domain !== '' ? $main_domain : $host;
            sse_message("🌐 Configuring Nginx for: $targetLabel...");
            
            // Check if Let's Encrypt certificates exist
            $useLetsEncrypt = false;
            if ($main_domain !== '') {
                $checkLe = $ssh->exec("if [ -f /etc/letsencrypt/live/" . escapeshellarg($main_domain) . "/fullchain.pem ]; then echo 'EXISTS'; fi");
                if (trim($checkLe) === 'EXISTS') {
                    $useLetsEncrypt = true;
                    sse_message("ℹ️ Found Let's Encrypt certificates. Using them.");
                }
            }
            
            $nginxConfig = get_nginx_config_multi($main_domain, $domains, $path, $rotation_enabled, $wildcard_enabled, $rotation_path, $rotation_slugs, $useLetsEncrypt);
            $nginxConfig = str_replace('/var/run/php/php-fpm.sock', $phpSock, $nginxConfig);
            
            if ($main_domain === '') {
                $ssh->exec("$sudo rm /etc/nginx/sites-enabled/default 2>/dev/null || true");
            }
            
            $configKey = nginx_config_key($main_domain);

            // Cleanup conflicting standalone configs for alias domains
            foreach ($domains as $d) {
                if ($d === '' || $d === $main_domain) continue;
                $aliasKey = nginx_config_key($d);
                // Only remove if it's not the main config key (just in case)
                if ($aliasKey !== $configKey) {
                    $ssh->exec("$sudo rm /etc/nginx/sites-enabled/$aliasKey 2>/dev/null || true");
                    $ssh->exec("$sudo rm /etc/nginx/sites-available/$aliasKey 2>/dev/null || true");
                }
            }

            write_nginx($ssh, $sudo, $configKey, $nginxConfig);
            sse_message("✅ Nginx configured and reloaded.");

            // Post-Deploy Health Check
            sse_message("🏥 Performing Post-Deploy Health Check...");
            
            $checkPath = '/';
            if ($rotation_enabled && !empty($rotation_path) && !empty($rotation_slugs)) {
                $checkPath = '/' . trim($rotation_path, '/') . '/' . $rotation_slugs[0];
                sse_message("ℹ️ Checking rotation path: $checkPath");
            }

            $hostHeader = $main_domain !== '' ? "-H 'Host: $main_domain'" : "";
            $checkCmd = "curl -s -o /dev/null -w '%{http_code}' $hostHeader " . escapeshellarg("http://localhost" . $checkPath);
            $httpCode = trim($ssh->exec($checkCmd));
            
            if ($httpCode >= 200 && $httpCode < 400) {
                sse_message("✅ Health Check Passed: Localhost returned HTTP $httpCode");
            } else {
                sse_message("⚠️ Health Check Warning: Localhost returned HTTP $httpCode. Check Nginx logs.", 'warning');
            }

            if ($main_domain !== '') {
                $publicUrl = "http://$main_domain" . $checkPath;
                $codePublic = trim($ssh->exec("curl -s -o /dev/null -w '%{http_code}' " . escapeshellarg($publicUrl)));
                sse_message("ℹ️ Public URL Check ($publicUrl): HTTP $codePublic");
            }

        } catch (Exception $e) {
            sse_message("⚠️ Nginx Setup Warning: " . $e->getMessage(), 'warning');
        }

        // Cleanup local zip
        unlink($zipFile);

        sse_finish("DONE_DEPLOY", $modeLabel);
        exit;
    }

    if ($action === 'ssl') {
        sse_message("🔒 Starting SSL Configuration (Certbot)...");
        
        try {
            $ssh = new SSH2($host, $port);
            if (!$ssh->login($user, $password)) {
                throw new Exception("Login failed.");
            }

            if ($main_domain === '') {
                throw new Exception("Main domain not configured.");
            }

            // Install Certbot if missing (Ubuntu/Debian)
            $sudo = ($user === 'root') ? '' : 'sudo ';
            $checkCertbot = "command -v certbot";
            if (!$ssh->exec($checkCertbot)) {
                sse_message("Installing Certbot...");
                $ssh->exec("$sudo apt-get update");
                $ssh->exec("DEBIAN_FRONTEND=noninteractive $sudo apt-get install -y certbot python3-certbot-nginx");
                
                // Reconnect to ensure clean state after installation
                $ssh = ssh_reconnect($ssh, $host, $port, $user, $password);
                
                // Verify installation
                if (!$ssh->exec($checkCertbot)) {
                     throw new Exception("Certbot installation failed. Please install manually or check VPS logs.");
                }
            }

            $certDomains = [$main_domain];
            // Always include additional domains in Certbot request if they are listed
            if (!empty($domains)) {
                $certDomains = array_merge($certDomains, $domains);
            }
            $certDomains = array_values(array_filter(array_unique(array_map('normalize_domain', $certDomains))));

            if ($wildcard_enabled) {
                sse_message("ℹ️ Wildcard enabled in Nginx. Certbot will certify listed domains only (HTTP-01).");
            }

            $certNames = [];
            foreach ($certDomains as $d) {
                foreach (domain_variants($d) as $name) {
                    $certNames[$name] = true;
                }
            }
            $certNames = array_values(array_keys($certNames));
            sort($certNames);

            $certbotArgs = [];
            foreach ($certNames as $name) {
                $certbotArgs[] = '-d ' . escapeshellarg($name);
            }
            $certbotArgs = implode(' ', $certbotArgs);

            // DNS Pre-check
            sse_message("🔍 Verifying DNS records...");
            $vpsIp = gethostbyname($host); // Resolve VPS hostname to IP if needed
            foreach ($certDomains as $d) {
                if ($d === $host) continue;
                $domainIp = gethostbyname($d);
                if ($domainIp !== $vpsIp && $domainIp !== $host) {
                     sse_message("⚠️ DNS Warning: $d resolves to $domainIp, but VPS is $host. Certbot might fail.", 'warning');
                } else {
                     sse_message("✅ DNS Verified: $d -> $domainIp");
                }
            }

            sse_message("Running Certbot for " . implode(', ', $certNames) . "...");
            $cmd = "$sudo certbot --nginx $certbotArgs --non-interactive --agree-tos --register-unsafely-without-email --redirect";
            
            $ssh->setTimeout(120); // Give it time
            $output = (string)$ssh->exec($cmd);
            sse_message($output);

            if (strpos($output, 'Congratulations') === false && strpos($output, 'Certificate not yet due') === false) {
                 throw new Exception("Certbot failed to obtain certificate. Check output for details.");
            }

            sse_message("✅ SSL Configured Successfully!", 'success');
            sse_message("DONE_SSL");

        } catch (Exception $e) {
            sse_message("❌ SSL Error: " . $e->getMessage(), 'error');
            exit;
        }
        exit;
    }

    if ($action === 'delete_uninstall') {
        sse_message("⚠️ Starting cleanup sequence...");
        
        try {
            $ssh = new SSH2($host, $port);
            if (!$ssh->login($user, $password)) {
                throw new Exception("Login failed.");
            }
            sse_message("✅ SSH Connected.");

            $sudo = ($user === 'root') ? '' : 'sudo ';

            // 1. Stop Worker and Background Processes
            sse_message("🛑 Stopping worker and background processes...");
            $ssh->exec("$sudo pkill -f 'php index.php worker' || true");
            
            // Reconnect to avoid channel issues
            if (method_exists($ssh, 'disconnect')) $ssh->disconnect();
            $ssh = null;
            $ssh = new SSH2($host, $port);
            if (!$ssh->login($user, $password)) throw new Exception("Relogin failed.");
            
            $ssh->exec("$sudo pkill -f 'node .*consolidated.js' || true");
            
            // Reconnect again for Nginx ops
            if (method_exists($ssh, 'disconnect')) $ssh->disconnect();
            $ssh = null;
            $ssh = new SSH2($host, $port);
            if (!$ssh->login($user, $password)) throw new Exception("Relogin failed.");

            // 2. Remove Nginx Config
            $configKey = nginx_config_key($main_domain);
            sse_message("🗑️ Removing Nginx configuration: $configKey...");
            remove_nginx_config($ssh, $sudo, $configKey);

            // Reconnect to avoid channel issues
            if (method_exists($ssh, 'disconnect')) $ssh->disconnect();
            $ssh = null; // Force cleanup
            
            $ssh = new SSH2($host, $port);
            if (!$ssh->login($user, $password)) {
                 throw new Exception("Relogin failed.");
            }

            // 3. Remove Files
            sse_message("🗑️ Removing project files at $path...");
            $ssh->exec("rm -rf " . escapeshellarg($path));

            // 4. Remove SSL (Optional, best effort)
            if ($main_domain !== '') {
                 sse_message("🗑️ Attempting to remove SSL certificates...");
                 $ssh->exec("$sudo certbot delete --cert-name " . escapeshellarg($main_domain) . " --non-interactive || true");
            }

            sse_message("✅ Cleanup complete.", 'success');
            sse_message("DONE_CLEANUP");

        } catch (Exception $e) {
             sse_message("❌ Cleanup Error: " . $e->getMessage(), 'error');
        }
        exit;
    }
}
?>
<!DOCTYPE html>
<html lang="en" class="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>L1mk Deployer // Command Center</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&family=Inter:wght@400;600;800&display=swap" rel="stylesheet">
    <script>
        tailwind.config = {
            darkMode: 'class',
            theme: {
                extend: {
                    fontFamily: {
                        mono: ['"JetBrains Mono"', 'monospace'],
                        sans: ['Inter', 'sans-serif'],
                    },
                    colors: {
                        brand: {
                            50: '#f0f9ff',
                            500: '#0ea5e9',
                            600: '#0284c7',
                            900: '#0c4a6e',
                            950: '#082f49',
                        },
                        terminal: {
                            bg: '#09090b',
                            text: '#a1a1aa',
                            green: '#22c55e',
                            red: '#ef4444',
                            yellow: '#eab308',
                            blue: '#3b82f6'
                        }
                    },
                    animation: {
                        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                    }
                }
            }
        }
    </script>
    <link href="assets/css/style.css" rel="stylesheet">
</head>
<body class="min-h-screen flex flex-col antialiased bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-slate-900 via-[#020617] to-black">

    <!-- Header -->
    <header class="border-b border-white/10 bg-black/20 backdrop-blur-md sticky top-0 z-50">
        <div class="max-w-7xl mx-auto px-3 h-10 flex items-center justify-between">
            <div class="flex items-center gap-3 cursor-pointer" onclick="showView('home')">
                <div class="w-8 h-8 rounded bg-gradient-to-br from-brand-500 to-purple-600 flex items-center justify-center shadow-lg shadow-brand-500/20">
                    <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path></svg>
                </div>
                <h1 class="text-xl font-bold tracking-tight text-white">L1mk <span class="text-brand-500 font-mono">Deployer</span></h1>
            </div>
            <div class="flex items-center gap-4 text-sm">
                <div class="flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10">
                    <span class="relative flex h-2 w-2">
                      <span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
                      <span class="relative inline-flex rounded-full h-2 w-2 bg-green-500"></span>
                    </span>
                    <span class="text-gray-400">System Ready</span>
                </div>
            </div>
        </div>
    </header>

    <main class="flex-1 max-w-7xl mx-auto w-full p-3">
        
        <!-- View: Home (List of Servers) -->
        <div id="view-home" class="space-y-8">
            <div class="flex justify-between items-center">
                <h2 class="text-2xl font-bold text-white">Your Servers</h2>
                <button onclick="showView('add-server')" class="px-4 py-2 bg-brand-600 hover:bg-brand-500 text-white rounded-lg font-bold shadow-lg shadow-brand-500/30 transition-all duration-200 flex items-center gap-2">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path></svg>
                    Add VPS
                </button>
            </div>

            <div id="server-list" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <!-- Server cards will be injected here -->
                <?php if (empty($savedServers)): ?>
                    <div class="col-span-full flex flex-col items-center justify-center py-20 text-gray-500 border border-white/5 rounded-xl bg-white/5">
                        <svg class="w-16 h-16 mb-4 opacity-50" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14M12 5l7 7-7 7"></path></svg>
                        <p class="text-lg">No servers configured.</p>
                        <p class="text-sm">Click "Add VPS" to get started.</p>
                    </div>
                <?php else: ?>
                    <?php foreach ($savedServers as $index => $srv): ?>
                        <div class="bg-slate-900/50 border border-white/10 rounded-xl p-6 backdrop-blur-sm shadow-xl hover:border-brand-500/50 transition cursor-pointer group relative" onclick="openDeploy('<?php echo $index; ?>')">
                            <div class="flex justify-between items-start mb-4">
                                <div class="w-10 h-10 rounded bg-brand-500/10 flex items-center justify-center text-brand-500">
                                    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 00-2 2v4a2 2 0 002 2h14a2 2 0 002-2v-4a2 2 0 00-2-2m-2-4h.01M17 16h.01"></path></svg>
                                </div>
                                <button onclick="event.stopPropagation(); deleteServer('<?php echo $srv['id'] ?? ''; ?>')" class="text-gray-500 hover:text-red-500 p-1">
                                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
                                </button>
                            </div>
                            <h3 class="text-xl font-bold text-white mb-1"><?php echo htmlspecialchars($srv['host']); ?></h3>
                            <p class="text-sm text-gray-400 mb-4"><?php echo htmlspecialchars($srv['user']); ?> @ Port <?php echo htmlspecialchars($srv['port']); ?></p>
                            <?php $displayMainDomain = $srv['main_domain'] ?? ($srv['domain'] ?? ''); ?>
                            <?php $extraDomainsCount = is_array($srv['domains'] ?? null) ? count($srv['domains']) : 0; ?>
                            <?php if(!empty($displayMainDomain)): ?>
                                <div class="inline-block px-2 py-1 bg-blue-500/10 text-blue-400 text-xs rounded border border-blue-500/20 mb-2">
                                    <?php echo htmlspecialchars($displayMainDomain); ?>
                                    <?php if($extraDomainsCount > 0): ?>
                                        <span class="text-blue-300/80">+<?php echo $extraDomainsCount; ?></span>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                            <?php $allDomains = []; ?>
                            <?php if(!empty($displayMainDomain)) $allDomains[] = $displayMainDomain; ?>
                            <?php if(is_array($srv['domains'] ?? null)) $allDomains = array_merge($allDomains, $srv['domains']); ?>
                            <?php $allDomains = array_values(array_filter(array_unique($allDomains))); ?>
                            <?php if(count($allDomains) > 0): ?>
                                <p class="text-xs text-slate-400">
                                    Domains: <?php echo htmlspecialchars(implode(', ', array_slice($allDomains, 0, 4))); ?><?php echo (count($allDomains) > 4) ? '…' : ''; ?>
                                </p>
                            <?php endif; ?>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </div>

        <!-- View: Add Server -->
        <div id="view-add-server" class="hidden max-w-2xl mx-auto">
            <div class="mb-6 flex items-center gap-4">
                <button onclick="showView('home')" class="p-2 rounded-lg bg-white/5 hover:bg-white/10 text-white transition">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path></svg>
                </button>
                <h2 class="text-2xl font-bold text-white">Add New VPS</h2>
            </div>
            
            <form id="addServerForm" class="bg-slate-900/50 border border-white/10 rounded-xl p-8 backdrop-blur-sm shadow-xl space-y-6">
                <div class="grid grid-cols-2 gap-6">
                    <div class="col-span-2 relative input-group">
                        <input type="text" name="host" id="add_host" required class="block px-4 py-3 w-full text-sm text-white bg-black/20 rounded-lg border border-gray-700 focus:border-brand-500 focus:ring-1 focus:ring-brand-500 focus:outline-none peer placeholder-transparent" placeholder="1.2.3.4">
                        <label for="add_host" class="absolute text-sm text-gray-500 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-transparent px-2 peer-focus:px-2 peer-focus:text-brand-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-2">VPS IP Address</label>
                    </div>
                    <div class="relative input-group">
                        <input type="text" name="user" id="add_user" required value="root" class="block px-4 py-3 w-full text-sm text-white bg-black/20 rounded-lg border border-gray-700 focus:border-brand-500 focus:ring-1 focus:ring-brand-500 focus:outline-none peer placeholder-transparent" placeholder="root">
                        <label for="add_user" class="absolute text-sm text-gray-500 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-transparent px-2 peer-focus:px-2 peer-focus:text-brand-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-2">User</label>
                    </div>
                    <div class="relative input-group">
                        <input type="number" name="port" id="add_port" value="22" class="block px-4 py-3 w-full text-sm text-white bg-black/20 rounded-lg border border-gray-700 focus:border-brand-500 focus:ring-1 focus:ring-brand-500 focus:outline-none peer placeholder-transparent" placeholder="22">
                        <label for="add_port" class="absolute text-sm text-gray-500 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-transparent px-2 peer-focus:px-2 peer-focus:text-brand-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-2">Port</label>
                    </div>
                    <div class="col-span-2 relative input-group">
                        <input type="password" name="password" id="add_password" required class="block px-4 py-3 w-full text-sm text-white bg-black/20 rounded-lg border border-gray-700 focus:border-brand-500 focus:ring-1 focus:ring-brand-500 focus:outline-none peer placeholder-transparent" placeholder="••••••••">
                        <label for="add_password" class="absolute text-sm text-gray-500 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-transparent px-2 peer-focus:px-2 peer-focus:text-brand-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-2">SSH Password</label>
                    </div>
                    
                    <!-- Defaults for other fields -->
                    <div class="col-span-2 relative input-group">
                        <input type="text" name="main_domain" id="add_main_domain" class="block px-4 py-3 w-full text-sm text-white bg-black/20 rounded-lg border border-gray-700 focus:border-brand-500 focus:ring-1 focus:ring-brand-500 focus:outline-none peer placeholder-transparent" placeholder="example.com">
                        <label for="add_main_domain" class="absolute text-sm text-gray-500 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-transparent px-2 peer-focus:px-2 peer-focus:text-brand-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-2">Main Domain (Optional)</label>
                    </div>
                    <div class="col-span-2 relative input-group">
                        <textarea name="domains" id="add_domains" rows="3" class="block px-4 py-3 w-full text-sm text-white bg-black/20 rounded-lg border border-gray-700 focus:border-brand-500 focus:ring-1 focus:ring-brand-500 focus:outline-none peer placeholder-transparent resize-none" placeholder="domain2.com&#10;domain3.com"></textarea>
                        <label for="add_domains" class="absolute text-sm text-gray-500 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-transparent px-2 peer-focus:px-2 peer-focus:text-brand-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-2">Additional Domains (Comma/Newline)</label>
                    </div>
                    <div class="hidden">
                        <input type="hidden" name="rotation_enabled" id="add_rotation_enabled" value="1">
                    </div>
                    <div class="col-span-2 flex items-center justify-between gap-3 bg-black/10 border border-gray-700 rounded-lg px-4 py-3">
                        <label for="add_wildcard_enabled" class="text-sm text-gray-300 select-none">Enable Wildcard Subdomains (*.domain.com)</label>
                        <input type="checkbox" name="wildcard_enabled" id="add_wildcard_enabled" value="1" class="h-4 w-4 rounded border-gray-600 bg-black/20 text-brand-500 focus:ring-brand-500">
                    </div>
                    <input type="hidden" name="local_path" value="<?php echo htmlspecialchars(dirname(__DIR__)); ?>">
                    <input type="hidden" name="path" value="/var/www/html">
                </div>

                <div id="add-error" class="hidden p-4 bg-red-900/20 border border-red-900/50 text-red-200 rounded-lg text-sm"></div>

                <button type="submit" id="addServerBtn" class="w-full px-4 py-3 bg-brand-600 hover:bg-brand-500 text-white rounded-lg font-bold shadow-lg shadow-brand-500/30 transition-all duration-200 flex items-center justify-center gap-2">
                    Connect & Add Server
                </button>
            </form>
        </div>

        <!-- View: Deploy (Compact Theme) -->
        <div id="view-deploy" class="hidden grid grid-cols-1 lg:grid-cols-12 gap-0.5">
            <div class="col-span-12 flex items-center gap-1 mb-0 shrink-0">
                <button onclick="showView('home')" class="p-0.5 rounded-lg bg-white/5 hover:bg-white/10 text-white transition">
                    <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path></svg>
                </button>
                <h2 class="text-sm leading-none whitespace-nowrap font-bold text-white flex items-center gap-1.5"><span class="text-[10px] text-gray-600 font-medium uppercase tracking-wider">Deploy to</span> <span id="deploy-target-name" class="text-brand-500"></span></h2>
            </div>

            <!-- Left Panel: Configuration -->
            <section class="lg:col-span-4 flex flex-col h-full overflow-hidden">
                <form id="deployForm" class="flex-1 flex flex-col bg-slate-900/50 border border-white/10 rounded-xl overflow-hidden backdrop-blur-sm shadow-xl">
                    <input type="hidden" name="server_id" id="deploy_server_id">
                    
                    <div class="p-3 border-b border-white/5 bg-white/5 flex items-center justify-between shrink-0">
                        <h2 class="text-sm font-semibold text-white flex items-center gap-2">
                            <svg class="w-4 h-4 text-brand-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"></path><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path></svg>
                            Configuration
                        </h2>
                    </div>

                    <div class="p-3 overflow-y-auto space-y-3 custom-scrollbar flex-1">
                        <!-- Connection & Credentials (Compact) -->
                        <details class="bg-black/20 border border-gray-700/50 rounded-lg group">
                            <summary class="flex items-center justify-between px-3 py-2 cursor-pointer select-none text-gray-400 text-xs font-medium hover:text-white transition">
                                <span class="flex items-center gap-2">
                                    <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11.536 19.464a2.5 2.5 0 01-2.613 0l-3.232-1.616a2.5 2.5 0 010-4.473l5.068-2.534A6 6 0 0121 9z"></path></svg>
                                    Connection & Credentials
                                </span>
                                <svg class="w-3 h-3 transition-transform group-open:rotate-180" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path></svg>
                            </summary>
                            <div class="px-3 pb-3 pt-1 space-y-2 border-t border-gray-700/50">
                                <div class="relative input-group mt-2">
                                    <input type="text" name="local_path" id="deploy_local_path" required value="<?php echo htmlspecialchars(dirname(__DIR__)); ?>" class="block px-3 py-1.5 w-full text-xs text-white bg-black/20 rounded border border-gray-700 focus:border-brand-500 focus:outline-none placeholder-transparent" placeholder="Local Path">
                                    <label class="absolute text-[10px] text-gray-500 uppercase tracking-wider top-1.5 left-2 pointer-events-none transition-all peer-placeholder-shown:top-1.5 peer-focus:-top-2.5 peer-focus:text-brand-500 bg-slate-900/0 px-1">Local Path</label>
                                </div>

                                <div class="grid grid-cols-2 gap-2">
                                    <div class="col-span-2">
                                        <input type="text" name="host" id="deploy_host" required class="block px-3 py-1.5 w-full text-xs text-white bg-black/20 rounded border border-gray-700 focus:border-brand-500 focus:outline-none" placeholder="VPS IP">
                                    </div>
                                    <div>
                                        <input type="text" name="user" id="deploy_user" required class="block px-3 py-1.5 w-full text-xs text-white bg-black/20 rounded border border-gray-700 focus:border-brand-500 focus:outline-none" placeholder="User">
                                    </div>
                                    <div>
                                        <input type="number" name="port" id="deploy_port" class="block px-3 py-1.5 w-full text-xs text-white bg-black/20 rounded border border-gray-700 focus:border-brand-500 focus:outline-none" placeholder="Port">
                                    </div>
                                </div>

                                <div>
                                    <input type="password" name="password" id="deploy_password" required class="block px-3 py-1.5 w-full text-xs text-white bg-black/20 rounded border border-gray-700 focus:border-brand-500 focus:outline-none" placeholder="SSH Password">
                                </div>
                            </div>
                        </details>

                        <!-- Domain Configuration -->
                        <div class="space-y-2">
                            <h3 class="text-[10px] font-bold text-gray-600 uppercase tracking-wider">Domains</h3>
                            
                            <div>
                                <input type="text" name="main_domain" id="deploy_main_domain" class="block px-3 py-1.5 w-full text-xs text-white bg-black/20 rounded border border-gray-700 focus:border-brand-500 focus:outline-none" placeholder="Main Domain (e.g. example.com)" readonly>
                            </div>

                            <textarea name="domains" id="deploy_domains" class="hidden"></textarea>

                            <div class="bg-black/10 border border-gray-700/50 rounded-lg p-2 space-y-2">
                                <div class="flex gap-2">
                                    <input type="text" id="deploy_add_domain" class="flex-1 block px-2 py-1 w-full text-xs text-white bg-black/20 rounded border border-gray-700 focus:border-brand-500 focus:outline-none" placeholder="Add domain...">
                                    <button type="button" id="deployAddDomainBtn" class="px-2 py-1 text-xs bg-slate-800 hover:bg-slate-700 text-slate-200 rounded border border-slate-700">+</button>
                                </div>
                                <div id="deployDomainsPills" class="flex flex-wrap gap-1.5 min-h-[1.5rem]"></div>
                            </div>
                            
                            <!-- Options Grid -->
                            <div class="grid grid-cols-2 gap-2">
                                <div class="hidden">
                                    <input type="hidden" name="rotation_enabled" id="deploy_rotation_enabled" value="1">
                                </div>
                                <div class="flex items-center gap-2 bg-black/10 border border-gray-700/50 rounded px-2 py-1.5">
                                    <input type="checkbox" name="wildcard_enabled" id="deploy_wildcard_enabled" value="1" class="h-3 w-3 rounded border-gray-600 bg-black/20 text-brand-500 focus:ring-brand-500">
                                    <label for="deploy_wildcard_enabled" class="text-[11px] text-gray-300 select-none">Wildcard</label>
                                </div>
                            </div>

                            <!-- Verify & Auto Links (Visible) -->
                            <div class="bg-black/10 border border-gray-700/50 rounded-lg">
                                <div class="flex items-center justify-between px-3 py-2 text-gray-400 text-xs font-medium">
                                    <span class="flex items-center gap-2">
                                        <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                                        Verification & Status
                                    </span>
                                </div>
                                <div class="p-2 space-y-2 border-t border-gray-700/50">
                                    <div class="bg-black/20 rounded px-2 py-1.5">
                                        <div class="flex items-center justify-between mb-1">
                                            <span class="text-[11px] text-slate-400">Live Status</span>
                                            <button type="button" id="checkStatusBtn" class="text-[10px] text-emerald-400 hover:text-emerald-300">Refresh</button>
                                        </div>
                                        <div id="deployActiveDomains" class="flex flex-wrap gap-1 text-[10px] text-slate-500 min-h-[1.25rem]">
                                            <span class="text-slate-600">Waiting...</span>
                                        </div>
                                        <button type="button" id="loadActiveDomainsBtn" class="hidden"></button>
                                    </div>

                                    <div class="bg-black/20 rounded px-2 py-1.5">
                                        <div class="flex items-center justify-between mb-1">
                                            <span class="text-[11px] text-slate-400">Auto Links</span>
                                        </div>
                                        <div id="deployAutoLinks" class="flex flex-wrap gap-1 text-[10px]"></div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Maintenance Zone (Collapsed by default or compact) -->
                         <details class="group border-t border-white/5 pt-2">
                            <summary class="flex items-center gap-2 text-[11px] font-semibold text-gray-500 cursor-pointer hover:text-slate-300 select-none mb-2">
                                <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"></path><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path></svg>
                                Tools & Maintenance
                            </summary>
                            <div class="grid grid-cols-2 gap-2">
                                <button type="button" id="testBtn" class="px-2 py-1 text-[10px] bg-slate-800/50 hover:bg-slate-700 text-slate-400 hover:text-white rounded border border-slate-700 transition-colors">
                                    Test Conn
                                </button>
                                <button type="button" id="toolSslBtn" class="px-2 py-1 text-[10px] bg-purple-500/10 border border-purple-500/30 hover:bg-purple-500/20 text-purple-300 rounded transition-colors">
                                    SSL (Certbot)
                                </button>
                                <button type="button" id="removeDomainsBtn" class="px-2 py-1 text-[10px] bg-orange-900/20 hover:bg-orange-900/40 text-orange-400 border border-orange-900/30 rounded transition-colors">
                                    Remove Config
                                </button>
                                <button type="button" id="deleteBtn" class="px-2 py-1 text-[10px] bg-red-900/20 hover:bg-red-900/40 text-red-400 border border-red-900/30 rounded transition-colors">
                                    Delete Files & Uninstall
                                </button>
                            </div>
                        </details>
                    </div>

                    <!-- Sticky Footer Actions -->
                    <div class="p-3 border-t border-white/5 bg-slate-900/80 backdrop-blur space-y-2 shrink-0">
                        <button type="submit" id="deployBtn" class="w-full px-3 py-2 bg-brand-600 hover:bg-brand-500 text-white rounded-lg font-bold shadow-lg shadow-brand-500/30 transition-all flex items-center justify-center gap-2 text-sm">
                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path></svg>
                            Deploy (Full Setup)
                        </button>
                        <div class="grid grid-cols-2 gap-2">
                             <button type="button" id="updateCodeBtn" class="px-3 py-1.5 bg-blue-600/90 hover:bg-blue-500 text-white rounded-lg font-bold shadow-lg shadow-blue-500/20 transition-all text-xs">
                                Update Page (Code)
                             </button>
                             <button type="button" id="applyDomainsBtn" class="px-3 py-1.5 bg-emerald-600/90 hover:bg-emerald-500 text-white rounded-lg font-bold shadow-lg shadow-emerald-500/20 transition-all text-xs">
                                Update Domains
                             </button>
                        </div>
                        <div class="grid grid-cols-2 gap-2">
                            <button type="button" id="saveBtn" class="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg font-medium transition-all border border-slate-700 text-xs">
                                Save Configuration
                            </button>
                            <a id="adminFooterBtn" href="#" target="_blank" class="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-white rounded-lg font-medium transition-all border border-slate-700 text-xs text-center">
                                Admin Panel
                            </a>
                        </div>
                        <!-- Hidden Legacy Button -->
                        <button type="button" id="updateBtn" class="hidden">Update</button>
                    </div>
                </form>

                <div id="postDeployActions" class="hidden mt-2 bg-slate-900/50 border border-green-500/30 rounded-xl p-3 backdrop-blur-sm shadow-xl shrink-0">
                    <h3 class="text-sm font-semibold text-green-400 mb-2 flex items-center gap-2">Success</h3>
                    <div class="grid grid-cols-2 gap-2">
                        <button id="sslBtn" class="col-span-1 flex items-center justify-center gap-1 px-2 py-1.5 bg-purple-500/10 border border-purple-500/50 hover:bg-purple-500/20 text-purple-300 rounded text-xs font-bold transition-all">SSL (Certbot)</button>
                        <a id="adminBtn" href="#" target="_blank" class="hidden col-span-1 flex items-center justify-center gap-1 px-2 py-1.5 bg-slate-800 border border-slate-700 hover:bg-slate-700 text-white rounded text-xs font-bold transition-all">Admin Panel</a>
                    </div>
                </div>
            </section>

            <!-- Right Panel: Terminal -->
            <section class="lg:col-span-8 flex flex-col h-full overflow-hidden">
                <div class="flex-1 terminal-window rounded-xl overflow-hidden border border-white/10 flex flex-col shadow-2xl">
                    <div class="bg-black/40 px-3 py-2 border-b border-white/5 flex items-center justify-between shrink-0">
                        <div class="flex items-center gap-2">
                            <div class="flex space-x-1.5 mr-2">
                                <div class="w-2.5 h-2.5 rounded-full bg-red-500/80"></div>
                                <div class="w-2.5 h-2.5 rounded-full bg-yellow-500/80"></div>
                                <div class="w-2.5 h-2.5 rounded-full bg-green-500/80"></div>
                            </div>
                            <span class="text-[10px] font-mono text-gray-500">remote@vps:~</span>
                        </div>
                        <div class="text-[10px] text-gray-600 font-mono">SSH SECURE SHELL</div>
                    </div>
                    <div id="terminal" class="flex-1 p-4 overflow-y-auto font-mono text-xs space-y-1 text-gray-300 relative bg-black/90">
                         <div class="absolute inset-0 pointer-events-none bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-5"></div>
                        <div class="text-brand-500/50 mb-4">Welcome to L1mk Deployer v2.0<br>Select a server to begin...</div>
                    </div>
                </div>
            </section>
        </div>

    </main>

    <footer class="border-t border-white/5 py-6 mt-auto">
        <div class="max-w-7xl mx-auto px-6 text-center text-gray-600 text-sm">
            &copy; <?php echo date('Y'); ?> L1mk Deployment Systems. All rights reserved.
        </div>
    </footer>

    <script>
        // Data from PHP
        const savedServers = <?php echo json_encode($savedServers); ?>;
    </script>
    <script src="assets/js/app.js"></script>
</body>
</html>
